home/urls.py
from django.urls import path
from .views import MainPageView

app_name = 'home'

urlpatterns = [
    path('', MainPageView.as_view(), name='MainPageView'),
]

manager/urls.py
from django.urls import path
from .views import manager_page

app_name = 'manager'

urlpatterns = [
    path('', manager_page, name='manager_page'),
]

web/urls.py
from web import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account.views import LoginUserView, RegisterUserView, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', LoginUserView.as_view(), name='login'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),

    path('', include('home.urls')),

    path('manager/', include('manager.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/footer.html
<footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
              {{ footer_items.address|safe }}
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Reservations</h4>
            <p>
              <strong>Phone:</strong> {{ footer_items.phone|safe }}<br>
              <strong>Email:</strong> {{ footer_items.email|safe }}<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Working Hours</h4>
            <p>
                {{ footer_items.working_hours|safe }}
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="{{ footer_items.twitter }}" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="{{ footer_items.facebook }}" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="{{ footer_items.instagram }}" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="{{ footer_items.youtube }}" class="youtube"><i class="bi bi-youtube"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Atahan</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer><!-- End Footer -->

templates/layouts/nav.html
<nav id="navbar" class="navbar">
        <ul>
            <li><a href="#menu">Menu</a></li>
            <li><a href="#events">Events</a></li>
            <li><a href="#chefs">Chefs</a></li>
            <li><a href="#gallery">Gallery</a></li>
            {% if user.groups.all.0.name == 'manager' or user.is_staff %}
                <li><a href="{% url 'manager:manager_page' %}">Manager</a></li>
            {% endif %}
          <li><a href="#contact">Contact</a></li>
            <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
              <ul>
                <li><a href="#menu">Menu</a></li>
                <li><a href="#events">Events</a></li>
                <li><a href="#chefs">Chefs</a></li>
                <li><a href="#gallery">Gallery</a></li>
                <li><a href="#contact">Contact</a></li>  
              </ul>
          </li>  
        </ul>
      </nav><!-- .navbar -->

templates/layouts/welcome.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Turkmen Restaurant</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/main.css" %} rel="stylesheet">
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
      <a href="{% url "home:MainPageView" %}" class="logo d-flex align-items-center me-auto me-lg-0">
        <h1>Restaurant Aylin<span>.</span></h1>
      </a>
      {% include 'layouts/nav.html' %}
      <a class="btn-book-a-table" href="#book-a-table">Book a Table</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    </div>
  </header><!-- End Header -->

  <main id="main">
      {% block content %}
      {% endblock %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'layouts/footer.html' %}
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>


  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>
</body>
</html>